### ISSUE TITLE
Setup TypeScript

### ISSUE THREAD

**Issue by oliviergoulet5** [StudyMeet/whiteboard#1]
## Overview
It would be in our best interest to introduce type-safety to our code. Therefore, we should use TypeScript as the language of choice for the StudyMeet whiteboard.

## Details
The code should be written in the "src" directory and the `tsc` compiler should build. in the "dist" folder. There should be a `npm run start` command, a `npm run dist`, and a `npm run dev` command. 

## Tasks
- [x] Create "src" directory
- [x] Create "dist" directory
- [x] Create `npm run start` command
- [x] Add `npm run dist` command
- [x] Add `npm run dev` command

**Comment by oliviergoulet5** [comment]
Resolved in PR #4
