### ISSUE TITLE
Setup prettier with pre-commit hook

### ISSUE THREAD

**Issue by oliviergoulet5** [StudyMeet/whiteboard#2]
## Overview
Auto-formatting code is a necessity in order to preserve consistency in a code base. 

## Details
Setup Prettier with desired configurations. This will add code formatting. Next step is to add ~~husky~~ [git-auto-commit-action](https://github.com/stefanzweifel/git-auto-commit-action) for a pre-commit hook so that Prettier runs before any commit.

Refer to [this blog post](https://mskelton.medium.com/auto-formatting-code-using-prettier-and-github-actions-ed458f58b7df).

## Tasks
- [x] Create prettierrc file with desired configurations
- [x] Setup an `npm run format` command
- [ ] Setup git-auto-commit-action
~Setup husky precommit~

**Comment by oliviergoulet5** [comment]
Husky would work fine but I was also thinking about whether or not there are GitHub Actions which accomplish the same thing.

**Comment by oliviergoulet5** [comment]
Possible issue with the CI workflow. Keep tabs.
